### PR TITLE
Solution for Issue #199

### PR DESCRIPTION
**Pull request by agencyv**

### CODE REVIEW

**Comment by neveldo** [comment]
Ok for me, I merge the fix, thank a lot !!

**Comment by neveldo** [comment]
Ooops no, there is a little mistake : there is a missing semicolon at line 1758.

Could you replace `})` by `});` in your PR ?

**Comment by billyrennekamp** [comment]
hey sorry
i'm making a mess of this.
i tried to separate all of the pull requests using the github gui but i've gotten my user accounts mixed up and this pull isn't correct either.
i'm sorry it's getting all mixed up, maybe it's easier if you extract the few lines that you want in the repo and add them yourself?

**Comment by neveldo** [comment]
Don't worry, 

I think you missed a little point in order to keep the PR separated from each other. It seems that you commit directly on the master branch of your forked mapael repository, and then make PR. That is why your last PR contains also the commits from the previous PRs. To the code modification separated in each PR, you need to create a new branch in your forked repository from the master branch, for each PR you want to submit to the original repository.

1 / You need to start from a clean master branch, see here to reset your master branch : http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream , don't forget to keep elsewhere your code modifications before cleaning the master branch. 

2 / In order to create a fix for the issue #199 (for instance), you need to create a new branch for the fix :+1: 

`git checkout master && git pull origin master` // Switch to the master branch and update it from the origin
`git checkout -b fix-issue-199 // Create a new branch from the master one
`git add ...`
`git commit -m "commit message"`
`git push origin fix-issue-199` // push the commit(s) the branch fix-issue-199 into the remote origin
Then, you can now make a PR of the branch fix-issue-19 to the original repository

In order to make a second pull request, you need to checkout again the master branch, and create a new branch from it.

Tell me if you have time to do it, otherwise, I will do what you said, extract the lines and push it to the repo.

**Comment by billyrennekamp** [comment]
ah thank you for such clear instructions. I made the mistake of not branching soon enough before i think. i have made the pr for issue 199 and will go through now and make new ones for the other issues.

**Pull request merged**
