### PR TITLE
Fix responsive event regression

### PR DESCRIPTION
**Pull request by Indigo744**
Hello,

PR #343 introduces a regression: the window `onResize` event was no longer properly detached.

This PR fixes that (and also fixes some tests wrongly using globals).

### CODE REVIEW

**Comment by neveldo** [comment]
Hello @Indigo744, 

As your PR contains a lot of changes, I will take the proper time to review it. I give you a feedback asap !

**Comment by Indigo744** [comment]
There are actually not _that_ much :smile: 
The most important thing is for the onResize event.
For the tests, there are only a lot of "find & replace" because now I could use the `this.$map` instead of the selector.

**Comment by Indigo744** [comment]
Right! I factorized it and resolve some remaining comma'first styles.

**Comment by neveldo** [comment]
Nice, it's ok for me !

**Pull request merged**
