### PR TITLE
Move default options

### PR DESCRIPTION
**Pull request by Indigo744**
Next step to neveldo/jQuery-Mapael#117 :-)

### CODE REVIEW

**Comment by neveldo** [comment]
I didn't thought about that, maybe I'm wrong, but I think moving the default options here will prevent users to do something like this : `$.fn.mapael.defaultOptions = ...}` for overwriting mapael the default options with a custom object. Some users also overwrite some internal functions for adding custom behaviour : 

    $.fn.setTooltip = function(elem, $tooltip) {
        // Custom stuff
        $.fn.setTooltip(elem, $tooltip);
    }

Do you think there is a way to allow plugin exension / overwriting with the new architecture ?

**Comment by Indigo744** [comment]
Is there an advantage on redefining the default options instead of just passing the user options as parameters? I always thought that the defaults value should remains Mapael internal stuff.

Regarding the function overriding, they should still be able to do that I think. I will try and provide example (as well as example for multiple instance of mapael on the same page).

**Comment by Indigo744** [comment]
Nevermind, I do see the advantage of redefining the default options and overriding behaviours.
Do not merge my PR yet, I need some time to think of something better :-)

**Comment by Indigo744** [comment]
Ok, now I know how default options and function will be overridden. 
I'll explain it to the corresponding issue.
You can merge this PR for now, and I assure you this feature will not be lost!

**Comment by neveldo** [comment]
Nice, I trust you ! :)

Regarding the defaultOptions object, for my part, I have already overwritten some parts of it for specific needs, for instance in order to preserve the current background color of each area on mouseover : `$.fn.mapael.defaultOptions.map.defaultArea.attrsHover = {};` because by defaut, attrsHover for areas is set to : 

    attrsHover : {
        fill : "#f38a03",
        animDuration : 300
    }

But it may be not the best approach, maybe some parameters such as mousehover behavior or stroke options shouldn't be part of the defaultOptions object ?

However, I think in some cases, it could be useful for user to be able to overwrite this object in order to set the same default options to all the maps of the app. The jQuery plugin datatable' also allows this kind of overwritings : https://datatables.net/examples/advanced_init/defaults.html .

**Comment by Indigo744** [comment]
I see why there would be such a need :)
Also, I think it would be useful for user who are creating different instances of mapael with the same base.
Love the Datatable plugin! I use it a lot in another project. Great plugin :)

**Comment by neveldo** [comment]
Same for me, Datatable is an awesome plugin !

**Pull request merged**
