### PR TITLE
Fixed the update event when plotsOn option used

### PR DESCRIPTION
**Pull request by Licht-T**
Hi,

Previously, I created the pull request about 'plotsOn' option.
But it had the bug when the update event.
Here is the fix pull request.

### CODE REVIEW

**Comment by neveldo** [comment]
Hello,

I don't understand, in the diff, it seems there is more than just a fix, as there is code modifications related to links between plots ?

**Comment by Licht-T** [comment]
Hello,

You are right. This is related to links between plots.
Before modifications, we cannot make a link between plots which is created by `plotsOn` option.

**Comment by Indigo744** [comment]
@Licht-T Can you provide an example? Like a JSFiddle for instance? Then we can review and merge your PR. Thanks!

**Comment by Indigo744** [comment]
I reviewed the change and it's OK.

I simply factorize the center computation to reduce same code.

**Pull request merged**
