### PR TITLE
Add Canada map with Lambert conformal conic projection

### PR DESCRIPTION
**Pull request by Cabalist**
Hello,

Attached is map object for Canada that follows the guidelines set out [here](http://www.statcan.gc.ca/pub/92-195-x/2011001/other-autre/mapproj-projcarte/m-c-eng.htm).  It also looks nice!  This is in reference to #191 that I posted a long time ago.

We've done the math but right now this code does not seem to be in line with the current codestyle.  I am submitting this as a pull request with the hopes that someone else can offer some feedback on getting this fully inline with this package.   

Thanks!

### CODE REVIEW

**Comment by neveldo** [comment]
Hello @Cabalist ,

Thanks for your contribution ! I have checked your map of canada, and all is almost fine.

1 / You should identify the paths following [the canadian provinces IDs](https://en.wikipedia.org/wiki/ISO_3166-2:CA) instead of having IDs such as path3645, path3654, etc.

2 / You should push your new map to the [dedicated repository for additional maps](https://github.com/neveldo/mapael-maps) in a new "canada" directory.

Feel free to ask if you need help, and thanks again for your incoming contribution !

**Comment by Indigo744** [comment]
@Cabalist can you make your PR to https://github.com/neveldo/mapael-maps? Or should I go ahead and add it myself? Thanks :)

**Comment by Cabalist** [comment]
I never cleaned up the code and don't currently have time to.  I can make a pull request though in it's current state.

**Comment by Indigo744** [comment]
Please make a PR in mapael-maps and check "accept update from maintainers"
so I will be able to clean it.

Thanks.

**Comment by Cabalist** [comment]
Done.   Thank you!

**Pull request closed without merging**
