### PR TITLE
Changed animation when updatetrigger will be executed

### PR DESCRIPTION
**Pull request by pharindoko**
This has been done as areas with gradients will be displayed as ugly
black boxes when an update of the map will be made. svg issue

### CODE REVIEW

**Comment by Indigo744** [comment]
For test, here is a JSFiddle highlighting this issue: http://jsfiddle.net/TKUy4/288/

**Comment by neveldo** [comment]
Hello,

Thank you for adding a JSFiddle that highlights the issue. What do you think about the modification provided by pharindoko ? For my part, I'm not fond of playing with the opacity for fixing this issue ...

**Comment by Indigo744** [comment]
As you, I'm not fond of changing the normal behavior for an edge case used only by a small faction.
This is a limitation of Raphael : animation with gradients are not supported.
See DmitryBaranovskiy/raphael#192.
Two solutions:
- check this customAttributes solution mentioned in the Raphael thread
- tell somewhere in the doc that if yo are using gradient, then you have to use `animDuration: 0`

**Comment by neveldo** [comment]
Hello,

I agree with you, no workaround to try to fix this issue.

By the way, regarding the documentation, I will create asap a new repository for storing the documentation page (http://www.vincentbroute.fr/mapael/). It will allow us to update the documentation as the code changes and to publish the up-to-date documentation when releasing the version 2 .

**Comment by neveldo** [comment]
FYI, I initialized a new repository for the Mapael documentation : https://github.com/neveldo/mapael-documentation/blob/master/index.html (yes I know, its just a basic HTML page :-). I need to do some cleanings before exposing the other parts, but here is the most important one ...

**Pull request closed without merging**
